version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Set stable to be defalt toolchain
          command: rustup default stable
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo make
      # See: https://levans.fr/rust_travis_cache.html
      - run:
          name: Remove unnecessary caching file
          command: rm -rf /usr/local/cargo/registry
      - save_cache:
          paths:
            - /usr/local/cargo/
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
